### ISSUE TITLE
Template Recursion with product xform

### ISSUE THREAD

**Issue by weshoke** [AbletonAG/atria#13] opened 2016-01-03 17:43 UTC
Is there a way to generate a product of sequences using the `count` xform?

``` cpp
auto idx = atria::prelude::comp(atria::xform::take(2), atria::xform::count(0, 1));
auto vec = into_vector(atria::xform::product(idx), idx);
```

Generates the error:

```
atria/xform/transducer/product.hpp:100:18: fatal error: recursive template instantiation exceeded maximum depth of 256
    comp(product(std::forward<InputRangeT>(r)),
```

**Comment by ghost** [comment] 2016-01-04 00:04
Hi @weshoke:

The problem is that in your example `idx` is a transducer, but the arguments of `product` are _ranges_ (in the standard sense, i.e. something with a _begin_ and _end_ interators).

However, it is easy to turn the `idx` tranducer into a range using `sequence`, which is like a lazy `into_vector` (it returns a lazy range a-la boost range adaptor that transducers the inputs using a transducer, but does not store the results in memory). Since `idx` is a generator transducer, no input sequence is needed though. Like here:

```
auto idx = atria::xform::sequence(
    atria::prelude::comp(atria::xform::take(2), atria::xform::count(0, 1)));
auto vec = into_vector(atria::xform::product(idx), idx);
```

Note, also, that the library already provides an alias for `comp(take(...), count(...))` called `range(...)`, in the spirit of Python's homonym.

I have added your example as a test here: https://github.com/Ableton/atria/commit/c7d2ca1b348cca6d60682afddd8a8fbf8cf779eb

**Comment by weshoke** [comment] 2016-01-04 15:20
I had thought I needed to use `sequence`, but I got the same compilation error:

``` cpp
auto idx = atria::xform::sequence(atria::prelude::comp(atria::xform::take(2), atria::xform::count(0, 1)));
auto vec = into_vector(atria::xform::product(idx), idx);
```

```
atria/xform/transducer/product.hpp:100:18: fatal error: recursive template instantiation exceeded maximum depth of 256
    comp(product(std::forward<InputRangeT>(r)),
```

**Comment by ghost** [comment] 2016-01-05 13:15
Sorry, yeah, there is a bug on the product implementatiom that triggers the error. It's also fixed on that branch. Thanks for the report.

**Comment by weshoke** [comment] 2016-01-05 23:55
You're welcome.  I can verify that the fixed worked!

**Comment by ghost** [comment] 2016-02-12 11:05
@weshoke I managed to fix the Travis problems and merge the PR, closing this. I also merged your PR, thanks!!

**Closed as completed by ghost** 2016-02-12 11:05 UTC
